services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./log/nginx:/var/log/nginx
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    command: "nginx -g 'daemon off;'"
    environment: 
      - TZ=Asia/Jakarta
    networks:
      - web

networks:
  web:
    driver: bridge
